import: [config/compass.yaml]
world:
    file: world/obstructed-2.world
    covered_by_obstacles: 0.08297
    type: obstructed
robots:
    -
        name: pioneer1
        ranger_index: 0
        max_velocity: [0.5, 1.57] # [m/s rad/s]
        min_velocity: [-0.5, -1.57]
        marker_sensor_max_range: 1.5
    -
        name: pioneer2
        ranger_index: 0
        max_velocity: [0.5, 1.57] # [m/s rad/s]
        min_velocity: [-0.5, -1.57]
        marker_sensor_max_range: 1.5

