statistic:
    floorplan_name: floorplan1
    tile_size: [1.0, 1.0] # [m m]
    coverage_events: [0.5, 0.6, 0.7, 0.8, 0.9]
algorithm:
    type: nodecounting
    obstacle_stop_distance: 0.5 # m
    obstacle_avoid_distance: 1.0 # m
    obstacle_marker_distance: 1.2 # m
    marker_deploy_distance: 1.6 # m
world:
    gui: true
    file: world/test.world
stock:
    refill_count: 10
robots:
    -
        name: pioneer1
        ranger_index: 0
        max_velocity: [0.5, 1.57] # [m/s rad/s]
        min_velocity: [-0.5, -1.57]
        marker_sensor_max_range: 2.0

