algorithm:
    type: randomwalk
    obstacle_avoid_distance: 0.5 # m
    obstacle_marker_distance: 1.2 # m
    marker_deploy_distance: 1.6 # m
world:
    file: world/test.world
stock:
    refill_count: 10
robots:
    -
        name: pioneer1
        ranger_index: 0
        max_velocity: [0.5, 1.57] # [m/s rad/s]
        min_velocity: [-0.5, -1.57] # [m/s rad/s]
        marker_sensor_max_range: 2.0 # m

