client:
    host: localhost
    port: 6665
simulation:
    simulation_index: 0
stock:
    stock_name: markerStock
    refill_count: 10
    graphics_index: 1
robots:
    -
        name: pioneer1
        motor_index: 0
        ranger_index: 0
        graphics_index: 0
        max_velocity: [0.5, 1.57] # [m/s rad/s]
        min_velocity: [-0.5, -1.57]
        marker_sensor_range: 2.0

