#!/bin/bash

declare -i COUNT
COUNT=100
ORIGIN_X="-100"
ORIGIN_Y="-100"
OUT_FILE="markers.inc"

if [ $# != 0 ]
then
    COUNT=$1
    shift
fi

if [ $# > 1 ]
then
    ORIGIN_X="$1"
    shift
    ORIGIN_Y="$1"
    shift
fi

echo "Creating $COUNT markers originated in ($ORIGIN_X/$ORIGIN_Y)."
echo "Out file is: \"$OUT_FILE\"."

rm -f $OUT_FILE

for i in `seq 1 $COUNT`
do
    echo "marker( name \"marker$i\" pose [ $ORIGIN_X $ORIGIN_Y 0 0 ] )" >> $OUT_FILE
done

    
