#!/bin/bash

CURRDIR=$PWD
BASEDIR=$(cd "$(dirname "$0")"; pwd)
cd "$BASEDIR/.."

declare -i COUNT
COUNT=1
TERRAINS="open obstructed office"
ROBOT_COUNTS="1 2 4 8"
ALGORITHMS="nodecounting lrtastar wagner compass randomwalk"

if [ $# -gt 0 ]
then
    COUNT=$1
fi

mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j 8

START_TIME=$SECONDS

for algorithm in $ALGORITHMS;
do
    for terrain in $TERRAINS;
    do
        for robots in $ROBOT_COUNTS;
        do
            for i in $(seq 1 $COUNT);
            do
                echo "executing '$algorithm' in '$terrain' with $robots robots ($i)"
                ./MultiAgentExploration -f config/$terrain/$algorithm-$robots.yaml -t 90 -c 85 -g
            done
        done
    done
done

ELAPSED_TIME=$(($SECONDS - $START_TIME))
EL_HOUR=$(($ELAPSED_TIME / 3600))
ELAPSED_TIME=$(($ELAPSED_TIME % 3600))
EL_MIN=$(($ELAPSED_TIME / 60))
EL_SEC=$(($ELAPSED_TIME % 60))

echo "Finished. ${EL_HOUR}h ${EL_MIN}m ${EL_SEC}s taken."
