import: [config/randomwalk.yaml]
world:
    file: world/open-1.world
    covered_by_obstacles: 0.0444
    type: open
robots:
    -
        name: pioneer1
        ranger_index: 0
        max_velocity: [0.5, 1.57] # [m/s rad/s]
        min_velocity: [-0.5, -1.57]
        marker_sensor_max_range: 2.0

